# Pi Server configuration
#
# This file contains all settings and their documentation
# Settings that have a default value are commented out with their default value

# ------------------------------------------------------------------------------
# Server
#
# The server is made of two distinct components:
# - Application: various Pi Server APIs
# - Admin: health checks, metrics, etc.
# These components use different ports so they can be configured independently
# ------------------------------------------------------------------------------

server:

    # The maximum number of requests to queue before blocking the acceptors
    maxQueuedRequests: 1024
    # The amount of time a worker thread can be idle before being stopped
    idleThreadTimeout: 1 minute
    # The maximum time to wait for the server to cleanly shutdown before forcibly terminating it
    shutdownGracePeriod: 30 seconds

    # ------------------------------------------------------------------------------
    # Application
    # ------------------------------------------------------------------------------

    # The minimum number of threads to keep alive in the thread pool
    minThreads: 8
    # The maximum number of threads the thread pool is allowed to grow
    maxThreads: 1024

    applicationConnectors:

        # ------------------------------------------------------------------------------
        # HTTP connector
        # ------------------------------------------------------------------------------

        - type: http
          # The hostname to bind to
          #bindHost:
          # The TCP/IP port on which to listen for incoming connections
          port: 8080
          # The number of worker threads dedicated to accepting connections (the default value is based on the number of cores)
          #acceptorThreads:
          # The number of worker threads dedicated to sending and receiving data (the default value is based on the number of cores)
          #selectorThreads:
          # The size of the TCP/IP accept queue for the listening socket (the default value is OS-dependent)
          #acceptQueueSize:
          # The size of the header field cache
          #headerCacheSize: 512 bytes
          # The size of the buffer into which response content is aggregated before being sent to the client
          #outputBufferSize: 32 KiB
          # The maximum size of a request header
          #maxRequestHeaderSize: 8 KiB
          # The maximum size of a response header
          #maxResponseHeaderSize: 8 KiB
          # The size of the per-connection input buffer
          #inputBufferSize: 8 KiB
          # The maximum idle time for a connection
          #idleTimeout: 30 seconds
          # The minimum size of the buffer pool
          #minBufferPoolSize: 64 bytes
          # The maximum size of the buffer pool
          #maxBufferPoolSize: 64 KiB
          # The increment by which the buffer pool should be increased
          #bufferPoolIncrement: 1 KiB
          # Whether or not SO_REUSEADDR is enabled on the listening socket
          #reuseAddress: true
          # Whether or not to add the 'Server' header to each response
          #useServerHeader: false
          # Whether or not to add the 'Date' header to each response
          #useDateHeader: true

        # ------------------------------------------------------------------------------
        # HTTPS connector
        # ------------------------------------------------------------------------------

        #- type: https
          # The hostname to bind to
          #bindHost:
          # The TCP/IP port on which to listen for incoming connections
          #port: 8443
          # The number of worker threads dedicated to accepting connections (the default value is based on the number of cores)
          #acceptorThreads:
          # The number of worker threads dedicated to sending and receiving data (the default value is based on the number of cores)
          #selectorThreads:
          # The size of the TCP/IP accept queue for the listening socket (the default value is OS-dependent)
          #acceptQueueSize:
          # The size of the header field cache
          #headerCacheSize: 512 bytes
          # The size of the buffer into which response content is aggregated before being sent to the client
          #outputBufferSize: 32 KiB
          # The maximum size of a request header
          #maxRequestHeaderSize: 8 KiB
          # The maximum size of a response header
          #maxResponseHeaderSize: 8 KiB
          # The size of the per-connection input buffer
          #inputBufferSize: 8 KiB
          # The maximum idle time for a connection
          #idleTimeout: 30 seconds
          # The minimum size of the buffer pool
          #minBufferPoolSize: 64 bytes
          # The maximum size of the buffer pool
          #maxBufferPoolSize: 64 KiB
          # The increment by which the buffer pool should be increased
          #bufferPoolIncrement: 1 KiB
          # Whether or not SO_REUSEADDR is enabled on the listening socket
          #reuseAddress: true
          # Whether or not to add the 'Server' header to each response
          #useServerHeader: false
          # Whether or not to add the 'Date' header to each response
          #useDateHeader: true
          # The path to the Java key store which contains the host certificate and private key (required)
          #keyStorePath: PATH
          # The password used to access the key store (required)
          #keyStorePassword: PASSWORD
          # The type of key store (usually JKS, PKCS12, JCEKS, Windows-MY or Windows-ROOT)
          #keyStoreType: JKS
          # The JCE provider to use to access the key store
          #keyStoreProvider:
          # The path to the Java key store which contains the CA certificates used to establish trust
          #trustStorePath: PATH
          # The password used to access the trust store
          #trustStorePassword: PASSWORD
          # The type of trust store (usually JKS, PKCS12, JCEKS, Windows-MY or Windows-ROOT)
          #trustStoreType: JKS
          # The JCE provider to use to access the trust store
          #trustStoreProvider:
          # The password, if any, for the key manager
          #keyManagerPassword: PASSWORD
          # Whether or not client authentication is required
          #needClientAuth: false
          # Whether or not client authentication is requested
          #wantClientAuth:
          # The alias of the certificate to use
          #certAlias: ALIAS
          # The path to the file which contains the Certificate Revocation List
          #crlPath: PATH
          # Whether or not CRL Distribution Points (CRLDP) support is enabled
          #enableCRLDP: false
          # Whether or not On-Line Certificate Status Protocol (OCSP) support is enabled
          #enableOCSP: false
          # The maximum certification path length
          #maxCertPathLength:
          # The location of the OCSP responder
          #ocspResponderUrl: URL
          # The name of the JCE provider to use for cryptographic support
          #jceProvider:
          # Whether or not to validate TLS certificates before starting
          #validateCerts: false
          # Whether or not to validate TLS peer certificates
          #validatePeers: false
          # List of protocols which are supported (SSLv3, TLSv1, etc.)
          #supportedProtocols: []
          # List of protocols which are excluded (SSLv3, TLSv1, etc.)
          #excludedProtocols: [SSL, SSLv2, SSLv2Hello, SSLv3]
          # List of cipher suites which are supported (TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, etc.)
          #supportedCipherSuites: []
          # List of cipher suites which are excluded (TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, etc.)
          #excludedCipherSuites: [.*_(MD5|SHA|SHA1)$]
          # Whether or not TLS renegotiation is allowed
          #allowRenegotiation: true

    # ------------------------------------------------------------------------------
    # Admin (see Application)
    # ------------------------------------------------------------------------------

    adminMinThreads: 1
    adminMaxThreads: 64

    adminConnectors:

        # ------------------------------------------------------------------------------
        # HTTP connector
        # ------------------------------------------------------------------------------

        - type: http
          port: 8081

    # ------------------------------------------------------------------------------
    # Compression
    # ------------------------------------------------------------------------------

    gzip:
        # If true:
        # - requests with "gzip" in the "Accept-Encoding" header will have their response entities compressed
        # - requests with "gzip" in the "Content-Encoding" header will have their request entities decompressed
        enabled: true
        # Response entities under this size are not compressed
        minimumEntitySize: 256 bytes
        # The size of the buffer to use when compressing
        bufferSize: 8 KiB

    # ------------------------------------------------------------------------------
    # Request logging
    # ------------------------------------------------------------------------------

    requestLog:

        # ------------------------------------------------------------------------------
        # Appenders
        # ------------------------------------------------------------------------------

        appenders:

            # File appender
            - type: file
              # The current log file
              currentLogFilename: /var/log/piserver-access.log
              # Log format (Logback pattern layout)
              logFormat: "%date{yyyy-MM-dd}\t%date{HH:mm:ss.SSS}\t%remoteIP\t%localIP:%localPort\t%requestMethod\t%requestURI\t%statusCode\t%bytesSent"
              # The time zone to which timestamps will be converted
              #timeZone: UTC
              # The maximum capacity of the blocking queue
              #queueSize: 256
              # When the blocking queue has only the capacity specified here remaining, it will drop statements of levels TRACE, DEBUG and INFO, keeping only those of levels WARN and ERROR
              # If this is set to -1, a default of queueSize / 5 is used
              # If this is set to 0, all statements are kept
              #discardingThreshold: -1
              # The file buffer size
              #bufferSize: 8KiB
              # If set to true, log statements will be immediately flushed to disk
              #immediateFlush: true
              # Whether or not to archive old events in separate files
              archive: false
              # The filename pattern for archived files (required if archive is true)
              # If maxFileSize is specified, rollover is size-based, and the pattern must contain %i for an integer index of the archived file. Otherwise rollover is date-based, and the pattern must contain %d, which is replaced with the date in yyyy-MM-dd form. If the pattern ends with .gz or .zip, files will be compressed as they are archived
              #archivedLogFilenamePattern:
              # The number of archived files to keep (0 means infinite number)
              #archivedFileCount: 5
              # The maximum size of the currently active file before a rollover is triggered
              #maxFileSize:
              # The total size of all files (oldest archives are deleted asynchronously when this size cap is exceeded)
              #totalSizeCap:

# ------------------------------------------------------------------------------
# Neo4j driver
# ------------------------------------------------------------------------------

neo4jDriver:
    uri: "bolt://localhost:7687"
    username: neo4j
    password: hubertUSA2016
    connectionTimeout: 1s
    minifyCypher: true
    databaseUpdateTimeout: 10 minutes


    # URI of the Neo4j server
    #uri: "bolt://localhost:7687"
    # Neo4j credentials
    #username: neo4j
    #password: PASSWORD
    # The maximum number of connections to keep in the pool
    #maxConnectionPoolSize: 100
    # The connection timeout
    #connectionTimeout: 30 seconds
    # The connection acquisition timeout
    #connectionAcquisitionTimeout: 60 seconds
    # The maximum amount of time during which a failed transaction is retried
    #maxTransactionRetryTime: 30 seconds
    # The maximum lifetime of a connection before it is evicted from the pool
    #maxConnectionLifetime: 1 hour
    # The timeout for a connection liveness check (if not specified, no liveness check is done)
    #connectionLivenessCheckTimeout: TIMEOUT
    # The database update timeout
    #databaseUpdateTimeout: 1 minute
    # If true, the Cypher queries are minified to be as compact as possible (this also affects query logging)
    #minifyCypher: false

# ------------------------------------------------------------------------------
# Security
# ------------------------------------------------------------------------------

security:
    # Time a user session can be idle before it is invalidated
    # If set to 0, user sessions never expire
    accessTokenExpirationTime: 0 seconds
#    externalSynchronization:
#        # The absolute location of the external synchronization file (must be executable)
#        #file: FILE
#        # The charset used by the output of the external synchronization
#        outputCharset: UTF-8
#        # The external synchronization execution timeout
#        executionTimeout: 1 minute
#    externalAuthentication:
#        # The absolute location of the external authentication file (must be executable)
#        #file: FILE
#        # The charset used by the input of the external authentication
#        inputCharset: UTF-8
#        # The external authentication execution timeout
#        executionTimeout: 5 seconds


# ------------------------------------------------------------------------------
# Validation
# ------------------------------------------------------------------------------

#validation:
    # If true, the P4 repo paths of IPVs on different lines must not overlap (if they have the same host)
    #checkP4RepoPathOverlap: true

    # ------------------------------------------------------------------------------
    # Hook
    # ------------------------------------------------------------------------------

    #hook:
        # The absolute location of the hook file (must be executable)
        #file: FILE
        # The charset used by the input of the hook
        #inputCharset: UTF-8
        # The charset used by the output of the hook
        #outputCharset: UTF-8
        # The hook execution timeout
        #executionTimeout: 5 seconds
        # The hook lock acquisition timeout
        #lockAcquisitionTimeout: 3 seconds

# ------------------------------------------------------------------------------
# API
# ------------------------------------------------------------------------------

api:
    # Default page size for the Public API
    #publicPaginationPageSize: 10000
    # Default page size for the CLI API
    #cliPaginationPageSize: 10000
    # Default number of concurrent requests for paginated endpoints in the CLI API
    #cliPaginationConcurrentRequests: 5
    # If false, the JSON in the response entities is minified to be as compact as possible
    prettyJson: true

# ------------------------------------------------------------------------------
# Events
# ------------------------------------------------------------------------------

events:

    # ------------------------------------------------------------------------------
    # Redis
    # ------------------------------------------------------------------------------

    redis:
        # Standalone Redis server
        standalone:
            host: localhost
            port: 6379

        # The Redis database to use
        #database: 0
        # The Redis credentials, if necessary
        #username:
        #password:
        # The Redis client name as seen by the Redis server
        #clientName: piserver
        # The connection timeout
        #timeout: 1 minute
        # If false, the JSON messages are minified to be as compact as possible
        #prettyJson: false

# ------------------------------------------------------------------------------
# Prometheus
# ------------------------------------------------------------------------------

prometheus:

    # If true, Prometheus metrics are collected
    enabled: false
    # If true, Prometheus Hotspot metrics are collected
    #hotspotMetrics: true
    # If true, Prometheus Jetty metrics are collected
    #jettyMetrics: true
    # If true, Prometheus API metrics are collected
    #apiMetrics: true
    # If true, Prometheus logging metrics are collected
    #loggingMetrics: true
    # If true, Prometheus Pi Server metrics are collected
    #piserverMetrics: true
    # If true, Dropwizard metrics are converted into Prometheus metrics
    #dropwizardMetrics: false

    # ------------------------------------------------------------------------------
    # Prometheus endpoint
    # ------------------------------------------------------------------------------

    endpoint:
        # If true, the Admin API exposes an endpoint that can be scraped by Prometheus
        enabled: true
        # Path of the Prometheus endpoint in the Admin API
        #path: prometheus

# ------------------------------------------------------------------------------
# Logging
#
# WARNING:
# Log statements at the DEBUG level may leak confidential data to whoever has access to them
# Passwords and private keys are never logged though
# ------------------------------------------------------------------------------

logging:

    # ------------------------------------------------------------------------------
    # Appenders
    # ------------------------------------------------------------------------------

    appenders:

        # Console appender
        - type: console
          threshold: ALL
          logFormat: "%-5level [%date{ISO8601}] %logger: %message%n%rootException"

    # ------------------------------------------------------------------------------
    # Root logger
    # ------------------------------------------------------------------------------

    # Log level of the root logger
    level: INFO

    # ------------------------------------------------------------------------------
    # Loggers
    # ------------------------------------------------------------------------------

    # loggers:
        #"com.example": DEBUG
